# Headless Service, for internal cluster access by other pods
apiVersion: v1
kind: Service

metadata:
  name: flow-test-network-v1
  namespace: flow

  labels:
    app: flow-test-net
    env: staging
    owner: Kan
    version: v1

spec:
  type: ClusterIP
  selector:
    app: flow-test-net
    env: staging
    version: v1
  # Headless Service, gives each pod a DNS address only.
  # Did not play well with cgo addrinfo lookup, which is used due to the DNS names ending in .local
  # best to use pure go implementation
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http # reference to the name of the port in your container config
    - name: grpc
      protocol: TCP
      port: 3569
      targetPort: grpc # reference to the name of the port in your container config