package admin

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"gosolo/module/component"
	"net"
	"net/http"
	"net/http/pprof"
	"os"
	"sync"
	"time"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"

	pb "gosolo/admin/admin"

	"gosolo/module/irrecoverable"
)

// 命令运行器也是一个组件,满足组件要求的接口
var _ component.Component = (*CommandRunner)(nil)

const CommandRunnerShutdownTimeout = 5 * time.Second

type CommandHandler func(ctx context.Context, request *CommandRequest) (interface{}, error)
type CommandValidator func(request *CommandRequest) error
type CommandRunnerOption func(*CommandRunner)

// CommandRequest is the structure of an admin command request.
type CommandRequest struct {
	// Data is the payload of the request, generated by the request initiator.
	// This is populated by the admin command framework and is available to both
	// Validator and Handler functions.
	// 请求的原始数据，json格式
	Data interface{}
	// ValidatorData may be optionally set by the Validator function, and will
	// then be available for use in the Handler function.
	// 把Data校验和转换成处理函数接口参数的数据
	ValidatorData interface{}
}

func WithTLS(config *tls.Config) CommandRunnerOption {
	return func(r *CommandRunner) {
		r.tlsConfig = config
	}
}

func WithGRPCAddress(address string) CommandRunnerOption {
	return func(r *CommandRunner) {
		r.grpcAddress = address
	}
}

func WithMaxMsgSize(size int) CommandRunnerOption {
	return func(r *CommandRunner) {
		r.maxMsgSize = size
	}
}

// admin命令和处理函数的映射
type CommandRunnerBootstrapper struct {
	handlers   map[string]CommandHandler
	validators map[string]CommandValidator
}

func NewCommandRunnerBootstrapper() *CommandRunnerBootstrapper {
	return &CommandRunnerBootstrapper{
		handlers:   make(map[string]CommandHandler),
		validators: make(map[string]CommandValidator),
	}
}

// CommandRunner的构造器，配置命令运行器，对命令和处理函数做映射关联
func (r *CommandRunnerBootstrapper) Bootstrap(logger zerolog.Logger, bindAddress string, opts ...CommandRunnerOption) *CommandRunner {
	handlers := make(map[string]CommandHandler)
	commands := make([]interface{}, 0, len(r.handlers))

	r.RegisterHandler("ping", func(ctx context.Context, req *CommandRequest) (interface{}, error) {
		return "pong", nil
	})

	r.RegisterHandler("list-commands", func(ctx context.Context, req *CommandRequest) (interface{}, error) {
		return commands, nil
	})

	for command, handler := range r.handlers {
		handlers[command] = handler
		commands = append(commands, command)
	}

	validators := make(map[string]CommandValidator)
	for command, validator := range r.validators {
		validators[command] = validator
	}

	commandRunner := &CommandRunner{
		handlers:         handlers,
		validators:       validators,
		grpcAddress:      fmt.Sprintf("%s/flow-node-admin.sock", os.TempDir()), // linux下面是/tmp, win下面是%TMP%, %TEMP%, %USERPROFILE%
		httpAddress:      bindAddress,
		logger:           logger.With().Str("admin", "command_runner").Logger(),
		startupCompleted: make(chan struct{}),
	}
	// 如果配置有自定义，更新配置
	for _, opt := range opts {
		opt(commandRunner)
	}

	return commandRunner
}

func (r *CommandRunnerBootstrapper) RegisterHandler(command string, handler CommandHandler) bool {
	if _, ok := r.handlers[command]; ok {
		return false
	}
	r.handlers[command] = handler
	return true
}

func (r *CommandRunnerBootstrapper) RegisterValidator(command string, validator CommandValidator) bool {
	if _, ok := r.validators[command]; ok {
		return false
	}
	r.validators[command] = validator
	return true
}

type CommandRunner struct {
	handlers   map[string]CommandHandler
	validators map[string]CommandValidator
	// 配置
	grpcAddress string // grpc的服务地址：一个本地sock文件
	httpAddress string // grpc的http网关
	maxMsgSize  int
	tlsConfig   *tls.Config
	logger      zerolog.Logger

	// wait for worker routines to be ready
	workersStarted sync.WaitGroup //对每一个协程的运行启动计数和等待

	// wait for worker routines to exit
	workersFinished sync.WaitGroup //对每一个协程的运行结束计数和等待

	// signals startup completion
	startupCompleted chan struct{} //对整个组件的启动等待，
}

func (r *CommandRunner) getHandler(command string) CommandHandler {
	return r.handlers[command]
}

func (r *CommandRunner) getValidator(command string) CommandValidator {
	return r.validators[command]
}

// 启动grpc服务和http网关
func (r *CommandRunner) Start(ctx irrecoverable.SignalerContext) {
	if err := r.runAdminServer(ctx); err != nil {
		ctx.Throw(fmt.Errorf("failed to start admin server: %w", err))
	}
	// 通知启动完成
	close(r.startupCompleted)
}

func (r *CommandRunner) Ready() <-chan struct{} {
	ready := make(chan struct{})

	// startupCompleted启动完成不代表协程启动完成，因为是异步处理的， 所以还要继续等worker的完成workersStarted
	go func() {
		<-r.startupCompleted
		r.workersStarted.Wait()
		close(ready)
	}()

	return ready
}

func (r *CommandRunner) Done() <-chan struct{} {
	done := make(chan struct{})

	go func() {
		<-r.startupCompleted
		r.workersFinished.Wait() // 等待所有服务关闭完成
		close(done)              // 通知外界
	}()

	return done
}

// 启动admin命令行服务的核心逻辑实现
func (r *CommandRunner) runAdminServer(ctx irrecoverable.SignalerContext) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	r.logger.Info().Msg("admin server starting up")
	// unix套接字用于本地进程间通信, 监听的是本地sock文件
	listener, err := net.Listen("unix", r.grpcAddress)
	if err != nil {
		return fmt.Errorf("failed to listen on admin server address: %w", err)
	}

	opts := []grpc.ServerOption{
		grpc.MaxRecvMsgSize(r.maxMsgSize),
		grpc.MaxSendMsgSize(r.maxMsgSize),
	}

	grpcServer := grpc.NewServer(opts...)
	// 注册admin服务到pb
	pb.RegisterAdminServer(grpcServer, NewAdminServer(r))

	r.workersStarted.Add(1)
	r.workersFinished.Add(1)
	go func() {
		defer r.workersFinished.Done()
		r.workersStarted.Done()
		// 在本地unix套接字上启动grpc服务
		if err := grpcServer.Serve(listener); err != nil {
			r.logger.Err(err).Msg("gRPC server encountered fatal error")
			ctx.Throw(err)
		}
	}()

	// 吧grpc服务转换为http网关
	// Initialize gRPC and HTTP muxers
	gwmux := runtime.NewServeMux()
	dialOpts := []grpc.DialOption{
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(r.maxMsgSize)),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	}
	err = pb.RegisterAdminHandlerFromEndpoint(ctx, gwmux, "unix:///"+r.grpcAddress, dialOpts)
	if err != nil {
		return fmt.Errorf("failed to register http handlers for admin service: %w", err)
	}

	mux := http.NewServeMux()
	mux.Handle("/", gwmux) // grpc 对应的api路由是/admin/run_command, 在proto文件中定义

	// 注册性能指标监控的接口
	// This adds an ability to use standard go tooling for performance troubleshooting e.g.:
	//  go tool pprof http://localhost:9002/debug/pprof/goroutine
	for _, name := range []string{"allocs", "block", "goroutine", "heap", "mutex", "threadcreate"} {
		mux.HandleFunc(fmt.Sprintf("/debug/pprof/%s", name), pprof.Handler(name).ServeHTTP)
	}
	mux.HandleFunc("/debug/pprof/trace", pprof.Trace)

	httpServer := &http.Server{
		Addr:      r.httpAddress,
		Handler:   mux,
		TLSConfig: r.tlsConfig,
	}

	// 启动http服务
	r.workersStarted.Add(1)
	r.workersFinished.Add(1)
	go func() {
		defer r.workersFinished.Done()
		r.workersStarted.Done()

		// Start HTTP server (and proxy calls to gRPC server endpoint)
		var err error
		if r.tlsConfig == nil {
			err = httpServer.ListenAndServe()
		} else {
			err = httpServer.ListenAndServeTLS("", "")
		}

		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			r.logger.Err(err).Msg("HTTP server encountered error")
			ctx.Throw(err)
		}
	}()

	// 关闭http服务:先关闭grpc, 再关闭http
	r.workersStarted.Add(1)
	r.workersFinished.Add(1)
	go func() {
		defer r.workersFinished.Done()
		r.workersStarted.Done()

		<-ctx.Done() // 等待ctx取消
		r.logger.Info().Msg("admin server shutting down")

		grpcServer.Stop()

		if httpServer != nil {
			shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), CommandRunnerShutdownTimeout)
			defer shutdownCancel()

			if err := httpServer.Shutdown(shutdownCtx); err != nil {
				r.logger.Err(err).Msg("failed to shutdown http server")
				ctx.Throw(err)
			}
		}
	}()

	return nil
}

// 解析处理命令，并执行对应的处理函数
func (r *CommandRunner) runCommand(ctx context.Context, command string, data interface{}) (interface{}, error) {
	r.logger.Info().Str("command", command).Msg("received new command")

	req := &CommandRequest{Data: data}

	// 在validator函数中，需要解析命令参数Data， 把解析后的数据放到ValidatorData中
	if validator := r.getValidator(command); validator != nil {
		if validationErr := validator(req); validationErr != nil {
			// for expected validation errors, return code InvalidArgument and the error text
			if IsInvalidAdminParameterError(validationErr) {
				return nil, status.Error(codes.InvalidArgument, validationErr.Error())
			}
			// for unexpected errors, return code Internal and log a warning
			r.logger.Err(validationErr).Msg("unexpected error validating admin request")
			return nil, status.Error(codes.Internal, validationErr.Error())
		}
	}

	var handleResult interface{}
	var handleErr error
	// 在validator函数中，使用解析后的数据ValidatorData
	if handler := r.getHandler(command); handler != nil {
		if handleResult, handleErr = handler(ctx, req); handleErr != nil {
			if errors.Is(handleErr, context.Canceled) {
				return nil, status.Error(codes.Canceled, "client canceled")
			} else if errors.Is(handleErr, context.DeadlineExceeded) {
				return nil, status.Error(codes.DeadlineExceeded, "request timed out")
			} else {
				r.logger.Err(handleErr).Msg("unexpected error handling admin request")
				s, _ := status.FromError(handleErr)
				return nil, s.Err()
			}
		}
	} else {
		return nil, status.Error(codes.Unimplemented, "invalid command")
	}

	return handleResult, nil
}

func (r *CommandRunner) GrpcAddress() string {
	// /tmp/flow-node-admin.sock
	return r.grpcAddress
}
